defaults: &defaults
  docker:
    - image: circleci/android:api-28-alpha
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:

  build:
    <<: *defaults
    steps:
    - checkout

    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "demo/build.gradle" }}
    - run:
        name: Assemble COMPAT SupportDebug
        command: ./gradlew :compat:assembleSupportDebug
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "demo/build.gradle" }}-{{ checksum  "library/build.gradle" }}

    - run:
        name: Assemble PLUGIN and publish to local
        command: ./gradlew :inappdevtools-plugin:publishToMavenLocal
    - run:
        name: Assemble NOOP Debug
        command: ./gradlew :noop:assembleDebug
    - run:
        name: Assemble COMPAT SupportDebug
        command: ./gradlew :compat:assembleSupportDebug
    - run:
        name: Assemble LIBRARY SupportDebug
        command: ./gradlew :library:assembleSupportDebug
    - run:
        name: Assemble DEMO SupportDebug
        command: ./gradlew :demo:assembleSupportDebug

  report:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "demo/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "demo/build.gradle" }}-{{ checksum  "library/build.gradle" }}

      - run:
          name: Lint report LIBRARY SupportDebug
          command: ./gradlew :library:lintSupportDebug
      - store_artifacts:
          name: Saving Lint report
          path: library/build/reports
          destination: library/reports

      - run:
          name: Lint report DEMO SupportDebug
          command: ./gradlew :demo:lintSupportDebug
      - store_artifacts:
          name: Saving Lint report
          path: demo/build/reports
          destination: demo/reports

      - run: 
          name: Sonar report ALL SupportDebug and upload to SonarCloud
          command: ./gradlew sonarqube -Dsonar.branch.name=${CIRCLE_BRANCH}

      - run: echo "Analized branch" ${CIRCLE_BRANCH}

  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "demo/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "demo/build.gradle" }}-{{ checksum  "library/build.gradle" }}

      - run: echo "Deploy job DISABLED"
#      - run:
#          name: Deploying...
#          command: ./gradlew -Prelease.useLastTag=true final



workflows:
  version: 2
  my-workflow:
    jobs:
    - build:        # Fired by commit on any branch (default) plus any tag
        filters:
          tags:
            only: /.*/

    - report:      # Fired by commit on any branch (default) plus any tag
        requires:
        - build
        filters:
          tags:
            only: /.*/

    - deploy:      # Fired by Github releases (tags starting with 'v.')
        requires:
          - report
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/