defaults: &defaults
  docker:
    - image: circleci/android:api-28-node
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:

  build:
    <<: *defaults
    steps:
    - checkout

    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "demo/build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "gradle/constants.gradle" }}

    - run:
        name: Local publish COMPAT SupportDebug
        command: ./gradlew :compat:publishToMavenLocal
    - run:
        name: Local publish COMPAT AndroidXDebug
        command: ./gradlew :compat:publishToMavenLocal -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - run:
        name: Assemble NOOP Debug
        command: ./gradlew :noop:assembleDebug

    - run:
        name: Assemble LIBRARY SupportDebug
        command: ./gradlew :library:assembleSupportDebug
    - run:
        name: Assemble DEMO SupportDebug
        command: ./gradlew :demo:assembleSupportDebug

    - run:
        name: Assemble LIBRARY AndroidxDebug
        command: ./gradlew :library:assembleAndroidxDebug -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true
    - run:
        name: Assemble DEMO AndroidxDebug
        command: ./gradlew :demo:assembleAndroidxDebug -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true

    - save_cache:
        paths:
          - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum "demo/build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "gradle/constants.gradle" }}

  report:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "demo/build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "gradle/constants.gradle" }}

      - run:
          name: Lint report LIBRARY SupportDebug
          command: ./gradlew :library:lintSupportDebug
      - store_artifacts:
          name: Saving Lint report
          path: library/build/reports
          destination: library/reports

      - run:
          name: Lint report DEMO SupportDebug
          command: ./gradlew :demo:lintSupportDebug
      - store_artifacts:
          name: Saving Lint report
          path: demo/build/reports
          destination: demo/reports

      - run: 
          name: Sonar report ALL SupportDebug and upload to SonarCloud
          command: ./gradlew build sonarqube
          #command: ./gradlew sonarqube -Dsonar.branch.name=${CIRCLE_BRANCH}

      - run: echo "Analized branch" ${CIRCLE_BRANCH}

  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "demo/build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "gradle/constants.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "demo/build.gradle" }}-{{ checksum  "library/build.gradle" }}-{{ checksum  "gradle/constants.gradle" }}

      - run: echo "Deploy job DISABLED"
#      - run:
#          name: Deploying...
#          command: ./gradlew -Prelease.useLastTag=true final



workflows:
  version: 2

  iadt-validation:
    jobs:

    - build:        # Fired by commit on any branch (default) plus any tag
        filters:
          tags:
            only: /.*/

    - report:      # Fired by commit on any branch (default) plus any tag
        requires:
        - build
        filters:
          tags:
            only: /.*/

    - deploy:      # Fired by Github releases (tags starting with 'v.')
        requires:
          - report
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/