defaults: &defaults
  docker:
    - image: circleci/android:api-28-alpha
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "sample/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}-{{ checksum  "library/build.gradle" }}

      - run:
          name: Run Lint report on library
          command: ./gradlew :inappdevtools:lint
      - store_artifacts:
          name: Save Lint report on library
          path: library/build/reports
          destination: library/reports

      - run:
          name: Run Lint report on sample
          command: ./gradlew :sample:lint
      - store_artifacts:
          name: Save Lint report on sample
          path: sample/build/reports
          destination: sample/reports

      - run: ./gradlew build
      - run: echo "Build job called"

  release:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "sample/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}-{{ checksum  "library/build.gradle" }}

      - run: echo "Release job called"
      #- run: ./gradlew -Prelease.useLastTag=true final


workflows:
  version: 2
  build-and-release:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/